### ISSUE TITLE
Would you be interested in an (academic) bibliography of relevant GPU hash table work?

### ISSUE THREAD

**Issue by jowens** [nosferalatu/SimpleConcurrentGPUHashTable#1]
I enjoyed your article. This is nice work!

**Comment by nosferalatu** [comment]
Thank you.
I would be interested. I've found many papers online about concurrent hash tables and GPU implementations. It seems like they all have different tradeoffs and constraints. I am interested in any other work in this area, too.

**Comment by jowens** [comment]
High-level survey: https://ieeexplore.ieee.org/abstract/document/8765787

Work from my group:
- https://escholarship.org/uc/item/2p48q0zg
- https://escholarship.org/uc/item/445536d6
- https://www.sciencedirect.com/science/article/pii/B9780123859631000046

Robin Hood hashing: https://hal.inria.fr/inria-00624777/document

Stadium hashing: https://ieeexplore.ieee.org/document/7429295/

Sparse-graph-inspired "HashGraph": https://arxiv.org/abs/1907.02900

Lemme know if you can't get PDFs out of these.

**Comment by HelliceSaouli** [comment]
Hello I'm trying to implement on the  GPU the famous 3D detection and registration algorithm called  "Point Pair Feature" and its based on hashing, is your hash table capable of fetching a list of all possible collision for a given key ?

**Comment by nosferalatu** [comment]
@HelliceSaouli If you want to find all the keys in the hash table that have the same hash value, then yes this hash table can do that. You can modify the `gpu_hashtable_lookup` function so that it does not stop iterating when `hashtable[slot].key == key`. Instead, it would check if `hash(keyToFind)==hash(hashtable[slot].key` and continue iterating in the hash table array until it found a kEmpty key.
