### ISSUE TITLE
Unity Compute Shader/Pseudo HLSL

### ISSUE THREAD

**Issue by b0nes164** [nosferalatu/SimpleConcurrentGPUHashTable#6]
Hi David, I made translation of your hashtable into a Unity Compute Shader, along with a demo file. I'd love to release it, but I'm new to GitHub and open source projects and I don't know what is the proper, respectful way to release code based on someone else's work. Would it be possible to add my code to this repo? Or should I just make my own repo, and credit you?

**Comment by nosferalatu** [comment]
Feel free to make your own repo. The code in this repo is in the public domain (see the LICENSE file) so you can do whatever you want with it. Thanks for asking though!

Let me know when your repo is public. I'd love to check it out.

**Comment by b0nes164** [comment]
The repo is up and public on my github! However, I encountered an absolutely bizarre bug with the deletion function that I don't really understand, and I was hoping you could shed some light on. For whatever reason, the delete function, as shown below, was not wiping any values from the hash table. 
```
void HashDelete(RWStructuredBuffer<KeyValue> _hashBuffer, uint key)
{
    uint slot = hash(key);

    while (true)
    {
        if (_hashBuffer[slot].key == key)
        {
            _hashBuffer[slot].value = s_empty;
            return;
        }
        if (_hashBuffer[slot].key == s_empty)
        {
            return;
        }
        slot = (slot + 1) & (hashBufferSize - 1);
}
```
Logically, the only code path that could result in such a scenario, "no delete," was if the function encountered an empty key slot, but that clearly could not account for an entire table failing to wipe. In order to test this further, I filled a small table to 100% load, where there could never be an empty key slot, but the deletion function still did not work. At this point I realized there must be some sort of compiler behavior that was to blame. Eventually, I did get deletions to work by shuffling the order of the conditionals, as shown below.
```
        if (_hashBuffer[slot].key == s_empty)
        {
            return;
        }
        if (_hashBuffer[slot].key == key)
        {
            _hashBuffer[slot].value = s_empty;
            return;
        }
```
Honestly I have no idea why this works. My theory is that despite being a static value, the value of the sentinel value, `s_empty` changes temporarily while it is being assigned to `_hashBuffer[slot].value,` and that this, in turn, trips the `s_empty` conditional in another branch due to flattening, which in turn calls the return exit. I'm not really sure though, and I am still very new to writing shader code, so again any light you could shed on the topic would be wonderful. And again, thanks for providing the example for the hash table implementation!

**Comment by nosferalatu** [comment]
I don't see how that change should affect the final contents of the buffer. Something strange is going on.

Looking through your code in the repo, the only thing I noticed is that the initialization kernel creates random numbers for the keys and values, but it doesn't prevent 0xffffffff from being picked. That's an issue, but it's not the problem you are seeing (that the delete kernel removes no keys).

I am suspicious that the code is reading back the data before the delete kernel has executed. However, Unity's documentation for `ComputeBuffer.getData()`: https://docs.unity3d.com/ScriptReference/ComputeBuffer.GetData.html says "If any GPU work has been submitted that writes to this buffer, Unity waits for the tasks to complete before it retrieves the requested data, guaranteeing this function returns the most up to date results". So, it should be doing the right thing, but perhaps getData() is not blocking until the delete kernel has completed its work? Although if that were the case... then reordering those two branches within the delete kernel should not matter.

It's also possible that Unity is not inserting a barrier between compute shader dispatch calls. It should insert a GPU barrier after the lookup kernel completes (because it's reading from the buffer) and before the delete kernel begins (because it's writing to the buffer). You could try manually inserting a GraphicsFence between the kernel (https://docs.unity3d.com/ScriptReference/Rendering.GraphicsFence.html) but it says that "GPUFences do not need to be used to synchronise a GPU task writing to a resource that will be read as an input by another. These resource dependencies are automatically handled by Unity." so it _should_ be inserting a barrier between the kernels, but maybe it's not.

FWIW, the CUDA code in my repo uses the default CUDA stream, which executes kernels synchronously (as if `cudaDeviceSynchronize()` was called before and after each CUDA operation), which is why you don't see any manual synchronization in that code. But my reading of the Unity docs is that it does synchronization for you, too.

If I were to debug this, I would try calling getData(), sleep for one second, then call getData() again. The first getData() _should_ block until the GPU is done, but maybe there's a bug there. If the CPU waits for one second and then gets the data again, the GPU must surely be done at that point. But I'm not sure that the problem is really synchronization or not (I don't see how a synchronization issue would be affected by the order of the branches within the shader).

**Comment by b0nes164** [comment]
Thanks for getting back to me. 

I fixed the random number generator by changing this line `return s--` to this `return s & (0xffffffff - 1)` (laziness).

On to the deletion bug. I was also under the impression that Unity created barriers between compute shader dispatches, but just to be safe I threw in some fences:
```
var fence = Graphics.CreateGraphicsFence(GraphicsFenceType.AsyncQueueSynchronisation, SynchronisationStageFlags.ComputeProcessing);
Graphics.WaitOnAsyncGraphicsFence(fence);
time = Time.realtimeSinceStartup;
compute.SetBuffer(deleteKernel, "HashBuffer", hashBuffer);
compute.SetBuffer(deleteKernel, "ValuesBuffer", valuesBuffer);
compute.Dispatch(deleteKernel, Mathf.CeilToInt(bufferSize / 1024f), 1, 1);
Graphics.WaitOnAsyncGraphicsFence(fence);
Debug.Log("Delete time for " + bufferSize + " random numbers: " + (Time.realtimeSinceStartup - time) + ".      " + ((1f / (Time.realtimeSinceStartup - time)) * bufferSize) + " keys/sec");
```
No luck here though, the bug persisted. 

I hadn't thought of `getData()` executing before the kernel finished, but it seemed to align with another issue with my project. As you may have seen on my repo page I was getting a rate of insertions and deletions of on the order of 10^12 per second at a load factor of 95% (32,000,000 / 33554432). Regardless of how fast my GPU is, this seemed way too high. I suspected that the way that I was calculating the time difference was incorrect because `Time.realtimeSinceStartup - time` could have been executing before the dispatch was completed. However, even with the fence in place (as seen above), I am still getting 10^12 insertions/lookups/deletions per second. Furthermore, I tried two different ways of ensuring the kernel finished its work. The first was to implement a wait function in a coroutine like so:
```
IEnumerator debug()
    {
        getDebugData();

        yield return new WaitForSeconds(1);

        getDebugData();

        yield return new WaitForSeconds(1);

        getDebugData();
    }
```
The second way was to use Unity's AsynchronousReadbackRequest [(https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadbackRequest.html)](https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadbackRequest.html) which should guarantee that the dispatch completes before it reads the data back into an array:
```
IEnumerator asyncDebug()
    {
        NativeArray<uint> test4 = new NativeArray<uint>(hashBufferSize * 2, Allocator.Persistent);

        var request = AsyncGPUReadback.Request(hashBuffer);
        yield return new WaitUntil(() => request.done);

        test4 = request.GetData<uint>();

        for (int i = 1; i < test4.Length; i+=2)
        {
            if (test4[i] != 0xffffffff)
            {
                Debug.Log("Deletion error at " + i);
            }
        }

        test4.Dispose();
    }
```
Unfortunately, the bug still persisted. So it seems like the kernel is finishing, but just not executing the way we wanted it to. Anyways I'll stop bothering you now, thanks for all the help! I'll make a thread on the Unity forums, and hopefully I'll be able to get to the bottom of this.
